name: data_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - absl-py=2.2.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - astunparse=1.6.3
  - blas=2.131
  - blas-devel=3.9.0
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - cfitsio=3.470
  - charset-normalizer=3.4.2
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - expat=2.7.1
  - flatbuffers=24.3.25
  - folium=0.19.5
  - fontconfig=2.14.1
  - fonttools=4.57.0
  - freetype=2.13.3
  - freexl=2.0.0
  - gast=0.6.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.10.6
  - geotiff=1.7.0
  - gettext=0.21.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - google-pasta=0.2.0
  - grpcio=1.71.0
  - h2=4.2.0
  - h5py=3.12.1
  - hdf4=4.2.13
  - hdf5=1.14.5
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.0
  - jpeg=9e
  - json-c=0.16
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kealib=1.5.0
  - keras=3.9.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgdal=3.6.2
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgrpc=1.71.0
  - libiconv=1.18
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libntlm=1.8
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxgboost=2.1.1
  - libxml2=2.13.8
  - libzip=1.8.0
  - lightgbm=4.6.0
  - llvm-openmp=20.1.4
  - lz4-c=1.9.4
  - mapclassify=2.8.1
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minizip=4.0.3
  - ml_dtypes=0.5.1
  - munkres=1.1.4
  - namex=0.0.9
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.10.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openblas=0.3.29
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.5.0
  - opt_einsum=3.4.0
  - optree=0.14.1
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - pixman=0.40.0
  - platformdirs=4.3.8
  - poppler=24.09.0
  - poppler-data=0.4.12
  - proj=9.3.1
  - prompt-toolkit=3.0.51
  - protobuf=5.29.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.1
  - pyaml=25.1.0
  - pycparser=2.22
  - pygments=2.19.1
  - pyogrio=0.10.0
  - pyparsing=3.2.3
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.9
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.2.10
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rich=14.0.0
  - scikit-learn=1.6.1
  - scikit-optimize=0.10.2
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=78.1.1
  - shapely=2.0.6
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.1
  - tensorflow-base=2.18.1
  - termcolor=3.1.0
  - threadpoolctl=3.6.0
  - tiledb=2.3.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - urllib3=2.4.0
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.0
  - xerces-c=3.2.4
  - xgboost=2.1.1
  - xyzservices=2025.4.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6